/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=caller/wrangler.jsonc --config=wrangler.jsonc --include-runtime=false --env-interface=CallerEnv caller/worker-configuration.d.ts` (hash: c41092ae068780f09c872cb584f9a2b8)
interface __BaseEnv_CallerEnv {
	NAMED_ENTRYPOINT: Service<typeof import("../src/index").NamedEntrypoint>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_CallerEnv {}
}
interface CallerEnv extends __BaseEnv_CallerEnv {}
